name: Pull Data

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install

      - name: Pull Proposals
        env:
          COVALENTHQ_API_KEY: ${{ secrets.COVALENTHQ_API_KEY }}
          INFURA_URL: ${{ secrets.INFURA_URL }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_CLIENT_EMAIL: ${{ secrets.SHEET_CLIENT_EMAIL }}
          SHEET_PRIVATE_KEY: ${{ secrets.SHEET_PRIVATE_KEY }}
        run: |
          node export-proposals.js
          node upload.js Proposals ./public/proposals.csv

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: public
